/*
 * File Name: KEYPAD_CONFIG.h
 * Creation Date: 07/24/2020
 * Author: Rehab
 * Description: Header File for keypad connection...
 */ 
 

//WE ARE USED ROWS AS INPUT AND COLUMNS AS OUTPUT
//KEYPAD MUST CONNECT IN THE BELOW WAY

/*
//IF LOWER NIBBLE ROWS
ROW0 ROW1 ROW2 ROW3
PIN0 PIN1 PIN2 PIN3

//IF LOWER NIBBLE COLUMNS
COLUMN0 COLUMN1 COLUMN2 COLUMN3
PIN0    PIN1    PIN2    PIN3
*/

/*
//IF HIGHER NIBBLE ROWS
ROW0 ROW1 ROW2 ROW3
PIN4 PIN5 PIN6 PIN7

//IF HIGHER NIBBLE COLUMNS
COLUMN0 COLUMN1 COLUMN2 COLUMN3
PIN4    PIN5    PIN6    PIN7
*/
#ifndef KEYPAD_CONFIG_H_
#define KEYPAD_CONFIG_H_

//FILES INCLUDING
#include "GPIO.h"

//KEYPAD CONNECTION
#define KEYPAD_PORT PORT_D
#define KEYPAD_ROWSPINS LOWER_NIBBLE
#define KEYPAD_COLUMNPINS HIGHER_NIBBLE

//KEYPAD CONNECTION MODE
#define KEYPAD_CONNECTION_MODE PULLUP_SW
#define PULLDOWN 0
#define PULLUP_HW 1
#define PULLUP_SW 2

#endif